"""m0 initial schema

Revision ID: af351a7a956b
Revises: 
Create Date: 2026-09-07 15:54:16.883352
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = 'af351a7a956b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('conv_id', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('conv_id')
    )
    op.create_table('poi',
    sa.Column('poi_id', sa.Text(), nullable=False),
    sa.Column('name_zh', sa.Text(), nullable=False),
    sa.Column('name_local', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('closed_days', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('open_from', sa.Time(), nullable=True),
    sa.Column('open_to', sa.Time(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Text(), nullable=False),
    sa.Column('accessible', sa.Boolean(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('poi_id')
    )
    op.create_index('ix_poi_city_category_status', 'poi', ['city', 'category', 'status'], unique=False)
    op.create_table('restaurant',
    sa.Column('rest_id', sa.Text(), nullable=False),
    sa.Column('name_zh', sa.Text(), nullable=False),
    sa.Column('name_local', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('cuisine', sa.Text(), nullable=False),
    sa.Column('price_band', sa.Text(), nullable=False),
    sa.Column('closed_days', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('open_from', sa.Time(), nullable=True),
    sa.Column('open_to', sa.Time(), nullable=True),
    sa.Column('dietary_support', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('child_friendly', sa.Boolean(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rest_id')
    )
    op.create_index('ix_restaurant_city_band_status', 'restaurant', ['city', 'price_band', 'status'], unique=False)
    op.create_table('supplier',
    sa.Column('supplier_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('contract_to', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('trace_log',
    sa.Column('trace_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conv_id', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.Text(), nullable=True),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_table('hotel',
    sa.Column('hotel_id', sa.Text(), nullable=False),
    sa.Column('name_zh', sa.Text(), nullable=False),
    sa.Column('name_local', sa.Text(), nullable=True),
    sa.Column('alias', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('nearest_station', sa.Text(), nullable=True),
    sa.Column('walk_min', sa.Integer(), nullable=True),
    sa.Column('advisor_notes', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    op.create_index('ix_hotel_city_tier_status', 'hotel', ['city', 'tier', 'status'], unique=False)
    op.create_table('message',
    sa.Column('msg_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conv_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.conv_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('rate_plan',
    sa.Column('rate_id', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('supplier_id', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('blackout_dates', postgresql.ARRAY(sa.Date()), nullable=True),
    sa.Column('net_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('price_basis', sa.Text(), nullable=False),
    sa.Column('meal_plan', sa.Text(), nullable=True),
    sa.Column('season_type', sa.Text(), nullable=False),
    sa.Column('season_uplift', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('rate_id')
    )
    op.create_index('ix_rate_plan_resource', 'rate_plan', ['resource_type', 'resource_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('requirement_card',
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('conv_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completeness', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('followups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conv_id'], ['conversation.conv_id'], ),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('conv_id', 'version', name='uq_card_conv_version')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Text(), nullable=False),
    sa.Column('name_zh', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('luggage_28', sa.Integer(), nullable=True),
    sa.Column('service_hours', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('generation_task',
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('replan_round', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['requirement_card.card_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_generation_task_status_hb', 'generation_task', ['status', 'heartbeat_at'], unique=False)
    op.create_table('plan_version',
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['requirement_card.card_id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'version')
    )
    op.create_table('room_type',
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('hotel_id', sa.Text(), nullable=False),
    sa.Column('name_zh', sa.Text(), nullable=False),
    sa.Column('bed_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('max_adults', sa.Integer(), nullable=False),
    sa.Column('max_children', sa.Integer(), nullable=False),
    sa.Column('min_child_age', sa.Integer(), nullable=True),
    sa.Column('extra_bed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index('ix_room_type_hotel_occ', 'room_type', ['hotel_id', 'max_occupancy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_type_hotel_occ', table_name='room_type')
    op.drop_table('room_type')
    op.drop_table('plan_version')
    op.drop_index('ix_generation_task_status_hb', table_name='generation_task')
    op.drop_table('generation_task')
    op.drop_table('vehicle')
    op.drop_table('requirement_card')
    op.drop_index('ix_rate_plan_resource', table_name='rate_plan')
    op.drop_table('rate_plan')
    op.drop_table('message')
    op.drop_index('ix_hotel_city_tier_status', table_name='hotel')
    op.drop_table('hotel')
    op.drop_table('trace_log')
    op.drop_table('supplier')
    op.drop_index('ix_restaurant_city_band_status', table_name='restaurant')
    op.drop_table('restaurant')
    op.drop_index('ix_poi_city_category_status', table_name='poi')
    op.drop_table('poi')
    op.drop_table('conversation')
    # ### end Alembic commands ###
